/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ReactionType = IDL.Variant({
  'hug' : IDL.Null,
  'heart' : IDL.Null,
  'kiss' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Drawing = IDL.Record({
  'id' : IDL.Text,
  'drawingData' : IDL.Text,
  'authorId' : IDL.Principal,
  'timestamp' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Memory = IDL.Record({
  'id' : IDL.Text,
  'authorId' : IDL.Principal,
  'timestamp' : Time,
  'caption' : IDL.Text,
  'photo' : ExternalBlob,
});
export const MessageType = IDL.Variant({
  'text' : IDL.Null,
  'emoji' : IDL.Text,
  'gifUrl' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'messageType' : MessageType,
  'timestamp' : Time,
  'senderId' : IDL.Opt(IDL.Principal),
});
export const Note = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'authorId' : IDL.Principal,
  'date' : Time,
});
export const DailyCheckInQuestion = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'authorId' : IDL.Principal,
  'date' : Time,
});
export const DailyAnswer = IDL.Record({
  'user' : IDL.Principal,
  'answer' : IDL.Text,
  'timestamp' : Time,
  'questionId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'name' : IDL.Text,
});
export const Reaction = IDL.Record({
  'userId' : IDL.Principal,
  'type' : ReactionType,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDailyQuestion' : IDL.Func([IDL.Text, Time], [IDL.Text], []),
  'addReaction' : IDL.Func([ReactionType], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDrawings' : IDL.Func([], [IDL.Vec(Drawing)], ['query']),
  'getAllMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(DailyCheckInQuestion)], ['query']),
  'getAllScheduledQuestions' : IDL.Func(
      [],
      [IDL.Vec(DailyCheckInQuestion)],
      ['query'],
    ),
  'getAnsweredDays' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAnswersForQuestion' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'currentUserAnswer' : IDL.Opt(DailyAnswer),
            'otherUserAnswer' : IDL.Opt(DailyAnswer),
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPastQuestions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getQuestionById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DailyCheckInQuestion)],
      ['query'],
    ),
  'getReactionCounts' : IDL.Func(
      [],
      [
        IDL.Record({
          'hugs' : IDL.Nat,
          'kisses' : IDL.Nat,
          'hearts' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getRecentReactions' : IDL.Func([], [IDL.Vec(Reaction)], ['query']),
  'getTodaysQuestion' : IDL.Func(
      [],
      [IDL.Opt(DailyCheckInQuestion)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasSubmittedAnswer' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'regenerateTodaysQuestion' : IDL.Func(
      [],
      [IDL.Opt(DailyCheckInQuestion)],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDrawing' : IDL.Func([IDL.Text], [IDL.Text], []),
  'saveMemory' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Text], []),
  'saveNote' : IDL.Func([IDL.Text, Time], [IDL.Text], []),
  'sendMessage' : IDL.Func([IDL.Text, MessageType], [IDL.Text], []),
  'submitDailyAnswer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateDailyQuestion' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
  'updateNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ReactionType = IDL.Variant({
    'hug' : IDL.Null,
    'heart' : IDL.Null,
    'kiss' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Drawing = IDL.Record({
    'id' : IDL.Text,
    'drawingData' : IDL.Text,
    'authorId' : IDL.Principal,
    'timestamp' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Memory = IDL.Record({
    'id' : IDL.Text,
    'authorId' : IDL.Principal,
    'timestamp' : Time,
    'caption' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const MessageType = IDL.Variant({
    'text' : IDL.Null,
    'emoji' : IDL.Text,
    'gifUrl' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'messageType' : MessageType,
    'timestamp' : Time,
    'senderId' : IDL.Opt(IDL.Principal),
  });
  const Note = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'authorId' : IDL.Principal,
    'date' : Time,
  });
  const DailyCheckInQuestion = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'authorId' : IDL.Principal,
    'date' : Time,
  });
  const DailyAnswer = IDL.Record({
    'user' : IDL.Principal,
    'answer' : IDL.Text,
    'timestamp' : Time,
    'questionId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'name' : IDL.Text,
  });
  const Reaction = IDL.Record({
    'userId' : IDL.Principal,
    'type' : ReactionType,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDailyQuestion' : IDL.Func([IDL.Text, Time], [IDL.Text], []),
    'addReaction' : IDL.Func([ReactionType], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDrawings' : IDL.Func([], [IDL.Vec(Drawing)], ['query']),
    'getAllMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllQuestions' : IDL.Func(
        [],
        [IDL.Vec(DailyCheckInQuestion)],
        ['query'],
      ),
    'getAllScheduledQuestions' : IDL.Func(
        [],
        [IDL.Vec(DailyCheckInQuestion)],
        ['query'],
      ),
    'getAnsweredDays' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAnswersForQuestion' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'currentUserAnswer' : IDL.Opt(DailyAnswer),
              'otherUserAnswer' : IDL.Opt(DailyAnswer),
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPastQuestions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getQuestionById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DailyCheckInQuestion)],
        ['query'],
      ),
    'getReactionCounts' : IDL.Func(
        [],
        [
          IDL.Record({
            'hugs' : IDL.Nat,
            'kisses' : IDL.Nat,
            'hearts' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getRecentReactions' : IDL.Func([], [IDL.Vec(Reaction)], ['query']),
    'getTodaysQuestion' : IDL.Func(
        [],
        [IDL.Opt(DailyCheckInQuestion)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasSubmittedAnswer' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'regenerateTodaysQuestion' : IDL.Func(
        [],
        [IDL.Opt(DailyCheckInQuestion)],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDrawing' : IDL.Func([IDL.Text], [IDL.Text], []),
    'saveMemory' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Text], []),
    'saveNote' : IDL.Func([IDL.Text, Time], [IDL.Text], []),
    'sendMessage' : IDL.Func([IDL.Text, MessageType], [IDL.Text], []),
    'submitDailyAnswer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateDailyQuestion' : IDL.Func([IDL.Text, IDL.Text, Time], [], []),
    'updateNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };