/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyAnswer {
  'user' : Principal,
  'answer' : string,
  'timestamp' : Time,
  'questionId' : string,
}
export interface DailyCheckInQuestion {
  'id' : string,
  'question' : string,
  'authorId' : Principal,
  'date' : Time,
}
export interface Drawing {
  'id' : string,
  'drawingData' : string,
  'authorId' : Principal,
  'timestamp' : Time,
}
export type ExternalBlob = Uint8Array;
export interface Memory {
  'id' : string,
  'authorId' : Principal,
  'timestamp' : Time,
  'caption' : string,
  'photo' : ExternalBlob,
}
export interface Message {
  'id' : string,
  'content' : string,
  'messageType' : MessageType,
  'timestamp' : Time,
  'senderId' : Principal,
}
export type MessageType = { 'text' : null } |
  { 'emoji' : string } |
  { 'gifUrl' : string };
export interface Note {
  'id' : string,
  'content' : string,
  'authorId' : Principal,
  'date' : Time,
}
export interface Reaction {
  'userId' : Principal,
  'type' : ReactionType,
  'timestamp' : Time,
}
export type ReactionType = { 'hug' : null } |
  { 'heart' : null } |
  { 'kiss' : null };
export type Time = bigint;
export interface UserProfile { 'displayName' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDailyQuestion' : ActorMethod<[string, Time], string>,
  'addReaction' : ActorMethod<[ReactionType], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllDrawings' : ActorMethod<[], Array<Drawing>>,
  'getAllMemories' : ActorMethod<[], Array<Memory>>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllQuestions' : ActorMethod<[], Array<DailyCheckInQuestion>>,
  'getAnsweredDays' : ActorMethod<[], Array<string>>,
  'getAnswersForQuestion' : ActorMethod<
    [string],
    [] | [
      {
        'currentUserAnswer' : [] | [DailyAnswer],
        'otherUserAnswer' : [] | [DailyAnswer],
      }
    ]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPastQuestions' : ActorMethod<[], Array<string>>,
  'getQuestionById' : ActorMethod<[string], [] | [DailyCheckInQuestion]>,
  'getReactionCounts' : ActorMethod<
    [],
    { 'hugs' : bigint, 'kisses' : bigint, 'hearts' : bigint }
  >,
  'getRecentReactions' : ActorMethod<[], Array<Reaction>>,
  'getTodaysQuestion' : ActorMethod<[], [] | [DailyCheckInQuestion]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasSubmittedAnswer' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDrawing' : ActorMethod<[string], string>,
  'saveMemory' : ActorMethod<[ExternalBlob, string], string>,
  'saveNote' : ActorMethod<[string, Time], string>,
  'sendMessage' : ActorMethod<[string, MessageType], string>,
  'submitDailyAnswer' : ActorMethod<[string, string], undefined>,
  'updateDailyQuestion' : ActorMethod<[string, string, Time], undefined>,
  'updateNote' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];